name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LLM_API_KEY: dummy
      DISABLE_MCP: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install Poetry
        run: pip install poetry==2.1.2
      - name: Install backend deps
        run: poetry install --with dev,test
      - name: Lint (ruff)
        run: poetry run ruff check .
      - name: Run backend tests (unit only)
        run: poetry run pytest -q tests/unit
      - name: Install frontend deps
        working-directory: frontend
        run: npm ci --no-audit --no-fund
      - name: Build frontend
        working-directory: frontend
        run: npm run build